-- AI 통신 요금제 상담 챗봇 초기 스키마 (v2 간소화: 상담 세션/메시지 제거, 최종 레포트만 유지, plans.json 호환)
-- PostgreSQL 17 / Supabase

-- 확장 활성화
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- 공통: updated_at 갱신 트리거
-- ============================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


-- ============================================================
-- 1. 사용자
-- ============================================================

CREATE TABLE public.users (
  id            UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  kakao_id      TEXT NOT NULL UNIQUE,
  email         TEXT,
  phone         TEXT,
  nickname      TEXT,
  age_group     TEXT,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  deleted_at    TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_select_self"
  ON public.users FOR SELECT
  TO authenticated
  USING (id = auth.uid());

CREATE POLICY "users_update_self"
  ON public.users FOR UPDATE
  TO authenticated
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

CREATE TRIGGER trg_users_updated
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


CREATE TABLE public.accessibility_settings (
  user_id     UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  easy_mode   BOOLEAN NOT NULL DEFAULT false,
  large_font  BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_accessibility_settings_user_id ON public.accessibility_settings(user_id);

ALTER TABLE public.accessibility_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "accessibility_settings_owner"
  ON public.accessibility_settings FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER trg_accessibility_settings_updated
  BEFORE UPDATE ON public.accessibility_settings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================
-- 2. 요금제 카탈로그 (plans.json integer id 호환)
-- ============================================================

CREATE TABLE public.plans (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                    TEXT NOT NULL,
  carrier                 TEXT NOT NULL DEFAULT 'LG U+',
  category                TEXT NOT NULL,
  target_age              TEXT NOT NULL,
  data_tier               TEXT NOT NULL,
  monthly_fee             INT NOT NULL,
  data                    TEXT NOT NULL,
  data_amount_gb          NUMERIC(10,2) NOT NULL,
  data_speed_after        TEXT,
  voice                   TEXT NOT NULL,
  call_amount_min         INT NOT NULL,
  message                 TEXT NOT NULL,
  sms_amount              INT NOT NULL,
  share_data              TEXT,
  tethering               TEXT,
  notes                   TEXT,
  benefits                JSONB NOT NULL DEFAULT '[]'::jsonb,
  ott_benefits            JSONB NOT NULL DEFAULT '[]'::jsonb,
  add_ons                 JSONB NOT NULL DEFAULT '[]'::jsonb,
  contract_period_months  INT,
  is_active               BOOLEAN NOT NULL DEFAULT true,
  sort_order              INT NOT NULL DEFAULT 0,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_plans_carrier ON public.plans(carrier);
CREATE INDEX idx_plans_category ON public.plans(category);
CREATE INDEX idx_plans_target_age ON public.plans(target_age);
CREATE INDEX idx_plans_data_tier ON public.plans(data_tier);
CREATE INDEX idx_plans_monthly_fee ON public.plans(monthly_fee);
CREATE INDEX idx_plans_is_active ON public.plans(is_active);
CREATE INDEX idx_plans_sort_order ON public.plans(sort_order);
CREATE INDEX idx_plans_carrier_target_age_active ON public.plans(carrier, target_age, is_active);
CREATE INDEX idx_plans_benefits_gin ON public.plans USING GIN (benefits);
CREATE INDEX idx_plans_ott_benefits_gin ON public.plans USING GIN (ott_benefits);
CREATE INDEX idx_plans_add_ons_gin ON public.plans USING GIN (add_ons);

ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "plans_select_active"
  ON public.plans FOR SELECT
  TO authenticated
  USING (is_active = true);

CREATE TRIGGER trg_plans_updated
  BEFORE UPDATE ON public.plans
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================
-- 3. 사용자 요금제 관리
-- ============================================================

CREATE TABLE public.saved_plans (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  plan_id     BIGINT NOT NULL REFERENCES public.plans(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_saved_plans_user_plan UNIQUE (user_id, plan_id)
);

CREATE INDEX idx_saved_plans_user_id ON public.saved_plans(user_id);
CREATE INDEX idx_saved_plans_plan_id ON public.saved_plans(plan_id);

ALTER TABLE public.saved_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "saved_plans_owner"
  ON public.saved_plans FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


CREATE TABLE public.current_plans (
  user_id     UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  plan_id     BIGINT NOT NULL REFERENCES public.plans(id),
  started_at  DATE NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_current_plans_plan_id ON public.current_plans(plan_id);

ALTER TABLE public.current_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "current_plans_owner"
  ON public.current_plans FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER trg_current_plans_updated
  BEFORE UPDATE ON public.current_plans
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================
-- 4. AI 상담
-- ============================================================

CREATE TABLE public.consultation_reports (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id             UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  summary_title       TEXT,
  summary             TEXT NOT NULL,
  analysis_input      JSONB DEFAULT '{}'::jsonb,
  current_plan_id     BIGINT REFERENCES public.plans(id),
  total_savings       INT NOT NULL DEFAULT 0,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_consultation_reports_user_id ON public.consultation_reports(user_id);
CREATE INDEX idx_consultation_reports_user_created ON public.consultation_reports(user_id, created_at DESC);
CREATE INDEX idx_consultation_reports_current_plan_id ON public.consultation_reports(current_plan_id);

ALTER TABLE public.consultation_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "consultation_reports_owner"
  ON public.consultation_reports FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER trg_consultation_reports_updated
  BEFORE UPDATE ON public.consultation_reports
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


CREATE TABLE public.report_recommendations (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  report_id     UUID NOT NULL REFERENCES public.consultation_reports(id) ON DELETE CASCADE,
  plan_id       BIGINT NOT NULL REFERENCES public.plans(id),
  reason        TEXT,
  savings       INT NOT NULL DEFAULT 0,
  sort_order    INT NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_report_recommendations_report_id ON public.report_recommendations(report_id);
CREATE INDEX idx_report_recommendations_plan_id ON public.report_recommendations(plan_id);
CREATE INDEX idx_report_recommendations_report_sort ON public.report_recommendations(report_id, sort_order);

ALTER TABLE public.report_recommendations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "report_recommendations_via_report"
  ON public.report_recommendations FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.consultation_reports r
      WHERE r.id = report_id AND r.user_id = auth.uid()
    )
  );


CREATE TABLE public.consultation_satisfactions (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  report_id   UUID NOT NULL UNIQUE REFERENCES public.consultation_reports(id) ON DELETE CASCADE,
  rating      TEXT NOT NULL,
  feedback    TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_consultation_satisfactions_report_id ON public.consultation_satisfactions(report_id);

ALTER TABLE public.consultation_satisfactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "consultation_satisfactions_via_report"
  ON public.consultation_satisfactions FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.consultation_reports r
      WHERE r.id = report_id AND r.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.consultation_reports r
      WHERE r.id = report_id AND r.user_id = auth.uid()
    )
  );


-- ============================================================
-- 5. 사용량 분석
-- ============================================================

CREATE TABLE public.usage_monthly (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id         UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  year_month      TEXT NOT NULL,
  data_used_gb    NUMERIC(10,2) NOT NULL DEFAULT 0,
  call_used_min   INT NOT NULL DEFAULT 0,
  sms_used_count  INT NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_usage_monthly_user_month UNIQUE (user_id, year_month)
);

CREATE INDEX idx_usage_monthly_user_id ON public.usage_monthly(user_id);

ALTER TABLE public.usage_monthly ENABLE ROW LEVEL SECURITY;
CREATE POLICY "usage_monthly_owner"
  ON public.usage_monthly FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER trg_usage_monthly_updated
  BEFORE UPDATE ON public.usage_monthly
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


CREATE TABLE public.usage_patterns (
  user_id           UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  avg_data_gb       NUMERIC(10,2) NOT NULL DEFAULT 0,
  avg_call_min      INT NOT NULL DEFAULT 0,
  avg_sms_count     INT NOT NULL DEFAULT 0,
  over_usage_data   BOOLEAN NOT NULL DEFAULT false,
  trend_6m          JSONB,
  trend_12m         JSONB,
  calculated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.usage_patterns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "usage_patterns_owner"
  ON public.usage_patterns FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER trg_usage_patterns_updated
  BEFORE UPDATE ON public.usage_patterns
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================
-- 6. 출석
-- ============================================================

CREATE TABLE public.attendances (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id       UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  date          DATE NOT NULL,
  reward_type   TEXT,
  reward_value  INT NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_attendances_user_date UNIQUE (user_id, date)
);

CREATE INDEX idx_attendances_user_id ON public.attendances(user_id);

ALTER TABLE public.attendances ENABLE ROW LEVEL SECURITY;
CREATE POLICY "attendances_owner"
  ON public.attendances FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


CREATE TABLE public.attendance_streaks (
  user_id            UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  current_streak     INT NOT NULL DEFAULT 0,
  longest_streak     INT NOT NULL DEFAULT 0,
  last_attended_at   DATE,
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.attendance_streaks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "attendance_streaks_owner"
  ON public.attendance_streaks FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER trg_attendance_streaks_updated
  BEFORE UPDATE ON public.attendance_streaks
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================
-- 7. 배지
-- ============================================================

CREATE TABLE public.badges (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name          TEXT NOT NULL,
  description   TEXT,
  image_url     TEXT,
  type          TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.badges ENABLE ROW LEVEL SECURITY;
CREATE POLICY "badges_select"
  ON public.badges FOR SELECT
  TO authenticated
  USING (true);


CREATE TABLE public.user_badges (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id       UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  badge_id      UUID NOT NULL REFERENCES public.badges(id) ON DELETE CASCADE,
  balance       INT NOT NULL DEFAULT 0,
  total_earned  INT NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_user_badges_user_badge UNIQUE (user_id, badge_id)
);

CREATE INDEX idx_user_badges_user_id ON public.user_badges(user_id);
CREATE INDEX idx_user_badges_badge_id ON public.user_badges(badge_id);

ALTER TABLE public.user_badges ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_badges_owner"
  ON public.user_badges FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER trg_user_badges_updated
  BEFORE UPDATE ON public.user_badges
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================
-- 8. 미션
-- ============================================================

CREATE TABLE public.missions (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name              TEXT NOT NULL,
  description       TEXT,
  condition_type    TEXT NOT NULL,
  condition_value   INT NOT NULL DEFAULT 0,
  reward_badge_id   UUID NOT NULL REFERENCES public.badges(id),
  reward_amount     INT NOT NULL DEFAULT 0,
  is_active         BOOLEAN NOT NULL DEFAULT true,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_missions_reward_badge_id ON public.missions(reward_badge_id);
CREATE INDEX idx_missions_is_active ON public.missions(is_active);

ALTER TABLE public.missions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "missions_select_active"
  ON public.missions FOR SELECT
  TO authenticated
  USING (is_active = true);

CREATE TRIGGER trg_missions_updated
  BEFORE UPDATE ON public.missions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


CREATE TABLE public.user_missions (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id       UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  mission_id    UUID NOT NULL REFERENCES public.missions(id) ON DELETE CASCADE,
  status        TEXT NOT NULL DEFAULT 'in_progress',
  completed_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_user_missions_user_mission UNIQUE (user_id, mission_id)
);

CREATE INDEX idx_user_missions_user_id ON public.user_missions(user_id);
CREATE INDEX idx_user_missions_mission_id ON public.user_missions(mission_id);

ALTER TABLE public.user_missions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_missions_owner"
  ON public.user_missions FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER trg_user_missions_updated
  BEFORE UPDATE ON public.user_missions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================
-- 9. 추천인
-- ============================================================

CREATE TABLE public.referrals (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  referrer_user_id    UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  referred_user_id    UUID REFERENCES public.users(id) ON DELETE SET NULL,
  referral_code       TEXT NOT NULL,
  status              TEXT NOT NULL DEFAULT 'pending',
  reward_given_at     TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_referrals_referred_user UNIQUE (referred_user_id),
  CONSTRAINT uq_referrals_code UNIQUE (referral_code)
);

CREATE INDEX idx_referrals_referrer_user_id ON public.referrals(referrer_user_id);

ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "referrals_owner"
  ON public.referrals FOR ALL
  TO authenticated
  USING (referrer_user_id = auth.uid() OR referred_user_id = auth.uid())
  WITH CHECK (referrer_user_id = auth.uid() OR referred_user_id = auth.uid());


-- ============================================================
-- 10. 게임
-- ============================================================

CREATE TABLE public.games (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  type        TEXT NOT NULL,
  name        TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
CREATE POLICY "games_select"
  ON public.games FOR SELECT
  TO authenticated
  USING (true);


CREATE TABLE public.game_results (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  game_id     UUID NOT NULL REFERENCES public.games(id) ON DELETE CASCADE,
  score       INT NOT NULL DEFAULT 0,
  played_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_game_results_user_id ON public.game_results(user_id);
CREATE INDEX idx_game_results_game_id ON public.game_results(game_id);

ALTER TABLE public.game_results ENABLE ROW LEVEL SECURITY;
CREATE POLICY "game_results_owner"
  ON public.game_results FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- ============================================================
-- 11. 상품 및 교환
-- ============================================================

CREATE TABLE public.products (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name              TEXT NOT NULL,
  description       TEXT,
  required_badges   INT NOT NULL DEFAULT 0,
  stock             INT,
  is_active         BOOLEAN NOT NULL DEFAULT true,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_products_is_active ON public.products(is_active);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "products_select_active"
  ON public.products FOR SELECT
  TO authenticated
  USING (is_active = true);

CREATE TRIGGER trg_products_updated
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


CREATE TABLE public.exchanges (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id       UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  product_id    UUID NOT NULL REFERENCES public.products(id),
  used_badges   INT NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_exchanges_user_id ON public.exchanges(user_id);
CREATE INDEX idx_exchanges_product_id ON public.exchanges(product_id);

ALTER TABLE public.exchanges ENABLE ROW LEVEL SECURITY;
CREATE POLICY "exchanges_owner"
  ON public.exchanges FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- ============================================================
-- 12. 쿠폰
-- ============================================================

CREATE TABLE public.coupons (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  exchange_id     UUID REFERENCES public.exchanges(id),
  user_id         UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  product_id      UUID NOT NULL REFERENCES public.products(id),
  barcode         TEXT NOT NULL,
  encrypted_code  TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'unused',
  used_at         TIMESTAMPTZ,
  expired_at      DATE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_coupons_barcode UNIQUE (barcode)
);

CREATE INDEX idx_coupons_user_id ON public.coupons(user_id);
CREATE INDEX idx_coupons_product_id ON public.coupons(product_id);
CREATE INDEX idx_coupons_exchange_id ON public.coupons(exchange_id);
CREATE INDEX idx_coupons_status ON public.coupons(status);
CREATE INDEX idx_coupons_expired_at ON public.coupons(expired_at);

ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "coupons_owner"
  ON public.coupons FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER trg_coupons_updated
  BEFORE UPDATE ON public.coupons
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


CREATE TABLE public.coupon_usages (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  coupon_id   UUID NOT NULL REFERENCES public.coupons(id) ON DELETE CASCADE,
  store_name  TEXT,
  used_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_coupon_usages_coupon_id ON public.coupon_usages(coupon_id);

ALTER TABLE public.coupon_usages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "coupon_usages_via_coupon"
  ON public.coupon_usages FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.coupons c
      WHERE c.id = coupon_id AND c.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.coupons c
      WHERE c.id = coupon_id AND c.user_id = auth.uid()
    )
  );


-- ============================================================
-- 13. 가입 신청
-- ============================================================

CREATE TABLE public.subscription_applications (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id             UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  target_plan_id      BIGINT NOT NULL REFERENCES public.plans(id),
  current_plan_id     BIGINT REFERENCES public.plans(id),
  status              TEXT NOT NULL DEFAULT 'submitted',
  identity_verified   BOOLEAN NOT NULL DEFAULT false,
  terms_agreed_at     TIMESTAMPTZ,
  requested_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at        TIMESTAMPTZ,
  canceled_at         TIMESTAMPTZ,
  cancel_reason       TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_subscription_applications_user_id ON public.subscription_applications(user_id);
CREATE INDEX idx_subscription_applications_target_plan_id ON public.subscription_applications(target_plan_id);
CREATE INDEX idx_subscription_applications_current_plan_id ON public.subscription_applications(current_plan_id);
CREATE INDEX idx_subscription_applications_user_requested ON public.subscription_applications(user_id, requested_at DESC);

ALTER TABLE public.subscription_applications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "subscription_applications_owner"
  ON public.subscription_applications FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TRIGGER trg_subscription_applications_updated
  BEFORE UPDATE ON public.subscription_applications
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


CREATE TABLE public.subscription_status_logs (
  id               UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  application_id   UUID NOT NULL REFERENCES public.subscription_applications(id) ON DELETE CASCADE,
  status           TEXT NOT NULL,
  changed_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  note             TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_subscription_status_logs_application_id ON public.subscription_status_logs(application_id);

ALTER TABLE public.subscription_status_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "subscription_status_logs_via_application"
  ON public.subscription_status_logs FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.subscription_applications sa
      WHERE sa.id = application_id AND sa.user_id = auth.uid()
    )
  );


CREATE TABLE public.terms_consents (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id         UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  application_id  UUID REFERENCES public.subscription_applications(id) ON DELETE CASCADE,
  term_type       TEXT NOT NULL,
  version         TEXT NOT NULL,
  agreed_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  ip              TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_terms_consents_user_id ON public.terms_consents(user_id);
CREATE INDEX idx_terms_consents_application_id ON public.terms_consents(application_id);

ALTER TABLE public.terms_consents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "terms_consents_via_application"
  ON public.terms_consents FOR ALL
  TO authenticated
  USING (
    user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.subscription_applications sa
      WHERE sa.id = application_id AND sa.user_id = auth.uid()
    )
  )
  WITH CHECK (
    user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.subscription_applications sa
      WHERE sa.id = application_id AND sa.user_id = auth.uid()
    )
  );


-- ============================================================
-- 14. 알림
-- ============================================================

CREATE TABLE public.notifications (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  type        TEXT NOT NULL,
  title       TEXT NOT NULL,
  body        TEXT,
  sent_at     TIMESTAMPTZ,
  read_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX idx_notifications_user_sent ON public.notifications(user_id, sent_at DESC);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "notifications_owner"
  ON public.notifications FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());
